package edu.globant.day10.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import edu.globant.day10.ws.ContactWs;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContactWsImplService", targetNamespace = "http://impl.ws.day10.globant.edu/", wsdlLocation = "http://localhost:8080/java-training-web/contactWs?wsdl")
public class ContactWsImplService
    extends Service
{

    private final static URL CONTACTWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTACTWSIMPLSERVICE_EXCEPTION;
    private final static QName CONTACTWSIMPLSERVICE_QNAME = new QName("http://impl.ws.day10.globant.edu/", "ContactWsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/java-training-web/contactWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACTWSIMPLSERVICE_WSDL_LOCATION = url;
        CONTACTWSIMPLSERVICE_EXCEPTION = e;
    }

    public ContactWsImplService() {
        super(__getWsdlLocation(), CONTACTWSIMPLSERVICE_QNAME);
    }

    public ContactWsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACTWSIMPLSERVICE_QNAME, features);
    }

    public ContactWsImplService(URL wsdlLocation) {
        super(wsdlLocation, CONTACTWSIMPLSERVICE_QNAME);
    }

    public ContactWsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACTWSIMPLSERVICE_QNAME, features);
    }

    public ContactWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContactWs
     */
    @WebEndpoint(name = "ContactWsImplPort")
    public ContactWs getContactWsImplPort() {
        return super.getPort(new QName("http://impl.ws.day10.globant.edu/", "ContactWsImplPort"), ContactWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactWs
     */
    @WebEndpoint(name = "ContactWsImplPort")
    public ContactWs getContactWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.day10.globant.edu/", "ContactWsImplPort"), ContactWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACTWSIMPLSERVICE_EXCEPTION!= null) {
            throw CONTACTWSIMPLSERVICE_EXCEPTION;
        }
        return CONTACTWSIMPLSERVICE_WSDL_LOCATION;
    }

}
