package edu.globant.day10.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import edu.globant.day10.ws.WebServiceDemo;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "WebServiceDemoImplService", targetNamespace = "http://impl.ws.day10.globant.edu/", wsdlLocation = "http://localhost:8080/java-training-web/webServiceDemo?wsdl")
public class WebServiceDemoImplService
	extends Service
{

	private final static URL WEBSERVICEDEMOIMPLSERVICE_WSDL_LOCATION;
	private final static WebServiceException WEBSERVICEDEMOIMPLSERVICE_EXCEPTION;
	private final static QName WEBSERVICEDEMOIMPLSERVICE_QNAME = new QName("http://impl.ws.day10.globant.edu/", "WebServiceDemoImplService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("http://localhost:8080/java-training-web/webServiceDemo?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		WEBSERVICEDEMOIMPLSERVICE_WSDL_LOCATION = url;
		WEBSERVICEDEMOIMPLSERVICE_EXCEPTION = e;
	}

	public WebServiceDemoImplService() {
		super(__getWsdlLocation(), WEBSERVICEDEMOIMPLSERVICE_QNAME);
	}

	public WebServiceDemoImplService(WebServiceFeature... features) {
		super(__getWsdlLocation(), WEBSERVICEDEMOIMPLSERVICE_QNAME, features);
	}

	public WebServiceDemoImplService(URL wsdlLocation) {
		super(wsdlLocation, WEBSERVICEDEMOIMPLSERVICE_QNAME);
	}

	public WebServiceDemoImplService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, WEBSERVICEDEMOIMPLSERVICE_QNAME, features);
	}

	public WebServiceDemoImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WebServiceDemoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return
	 *     returns WebServiceDemo
	 */
	@WebEndpoint(name = "WebServiceDemoImplPort")
	public WebServiceDemo getWebServiceDemoImplPort() {
		return super.getPort(new QName("http://impl.ws.day10.globant.edu/", "WebServiceDemoImplPort"), WebServiceDemo.class);
	}

	/**
	 *
	 * @param features
	 *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
	 * @return
	 *     returns WebServiceDemo
	 */
	@WebEndpoint(name = "WebServiceDemoImplPort")
	public WebServiceDemo getWebServiceDemoImplPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://impl.ws.day10.globant.edu/", "WebServiceDemoImplPort"), WebServiceDemo.class, features);
	}

	private static URL __getWsdlLocation() {
		if (WEBSERVICEDEMOIMPLSERVICE_EXCEPTION!= null) {
			throw WEBSERVICEDEMOIMPLSERVICE_EXCEPTION;
		}
		return WEBSERVICEDEMOIMPLSERVICE_WSDL_LOCATION;
	}

}
